# Generated by Django 3.1.1 on 2023-03-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
    ]
